### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by holybit** [yannk/perl-avro#2]
I perused the source but couldn't find any POD about how to go about using this module. Do you have any plans to add standard user docs like most modules on CPAN or was this just a throw away effort?

**Comment by dstates** [comment]
+1

I would like to use Avro for a production project, via a C++ and Perl program.  It seems your library would be a great addition to CPAN

**Comment by yannk** [comment]
https://github.com/apache/avro/tree/trunk/lang/perl
